project_id = "awbkbvpayomkauubomdo"

[functions.admin-bot]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false

[functions.send-moderation]
verify_jwt = false

[functions.send-edit-moderation]
verify_jwt = false

[functions.tg-reviews]
verify_jwt = false

[functions.tg-manage-product]
verify_jwt = false

[functions.tg-upload-product-media]
verify_jwt = false

[functions.tg-report-user]
verify_jwt = false

[functions.tg-give-reputation]
verify_jwt = false

[functions.tg-user-reputation]
verify_jwt = false